services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    ports:
      - "8000:8000"
    volumes:
      - media_data:/app/media
      - ./backend:/app  
      - static_data:/app/staticprofiles
    stdin_open: true
    tty: true
    
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - app


volumes:
  db_data:
  media_data:
  static_data: