# Generated by Django 5.1 on 2026-08-31 07:00

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_number_default'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='complaint',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
