# Generated by Django 5.1 on 2026-08-31 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_managers_complaint_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='complaints/attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Complaint Attachment',
                'verbose_name_plural': 'Complaint Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
